apiVersion: v2
description: A lightweight private npm proxy registry (sinopia fork)
name: verdaccio
version: 2.0.0
appVersion: 4.10.0
home: https://verdaccio.org
icon: https://cdn.verdaccio.dev/logos/default.png
sources:
  - https://verdaccio.org
  - https://github.com/verdaccio/verdaccio
keywords:
  - npm
  - registry
  - yarn
  - pnpm
  - javascript
  - nodejs
maintainers:
  - name: juanpicado
    email: juanpicado19@gmail.com
  - name: jhonmike
    email: jhon.msdev@gmail.com
