apiVersion: v1
description: A lightweight private npm proxy registry (sinopia fork)
name: verdaccio
version: 0.12.0
appVersion: 3.13.1
home: https://verdaccio.org
icon: https://cdn.verdaccio.dev/logos/default.png
sources:
- https://verdaccio.org
- https://github.com/verdaccio/verdaccio
keywords:
- npm
- nodejs
maintainers:
- name: juanpicado
  email: juanpicado19@gmail.com
- name: Jhon Mike
  email: jhon.msdev@gmail.com
